import { readFile, readdir } from 'node:fs/promises'
import { dirname, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const moduleDirectory = dirname(fileURLToPath(import.meta.url))

export const projectRoot = resolve(moduleDirectory, '..', '..')
export const generatedNotice = '<!-- Generated by govuk-design-md. Edit src/catalog records, then run npm run generate. -->'

function resolveContained(base, path) {
  const resolvedBase = resolve(base)
  const resolvedPath = resolve(resolvedBase, path)
  if (resolvedPath === resolvedBase || !resolvedPath.startsWith(`${resolvedBase}${sep}`)) {
    throw new Error(`generated path escapes its output directory: ${path}`)
  }
  return resolvedPath
}

export async function readJson(path) {
  return JSON.parse(await readFile(path, 'utf8'))
}

export async function loadSourceManifest(root = projectRoot) {
  return readJson(resolve(root, 'sources', 'govuk.json'))
}

export async function loadComponents(root = projectRoot) {
  const directory = resolve(root, 'src', 'catalog', 'components')
  const filenames = (await readdir(directory))
    .filter((filename) => filename.endsWith('.json'))
    .sort()

  const components = await Promise.all(
    filenames.map((filename) => readJson(resolve(directory, filename)))
  )

  return components.sort((left, right) => left.name.localeCompare(right.name, 'en-GB'))
}

export async function loadStyles(root = projectRoot) {
  const directory = resolve(root, 'src', 'catalog', 'styles')
  const filenames = (await readdir(directory))
    .filter((filename) => filename.endsWith('.json'))
    .sort()

  const styles = await Promise.all(
    filenames.map((filename) => readJson(resolve(directory, filename)))
  )

  return styles.sort((left, right) => left.name.localeCompare(right.name, 'en-GB'))
}

export async function loadPatterns(root = projectRoot) {
  const directory = resolve(root, 'src', 'catalog', 'patterns')
  const filenames = (await readdir(directory))
    .filter((filename) => filename.endsWith('.json'))
    .sort()

  const patterns = await Promise.all(
    filenames.map((filename) => readJson(resolve(directory, filename)))
  )

  return patterns.sort((left, right) => left.name.localeCompare(right.name, 'en-GB'))
}

export async function loadPackage(root = projectRoot) {
  return readJson(resolve(root, 'package.json'))
}

export async function loadTokens(root = projectRoot) {
  return readJson(resolve(root, 'tokens', 'govuk.tokens.json'))
}

export async function loadAiAdapters(root = projectRoot) {
  return readJson(resolve(root, 'sources', 'ai-adapters.json'))
}

export async function loadFrameworkAdapters(root = projectRoot) {
  return readJson(resolve(root, 'sources', 'framework-adapters.json'))
}

export function tokenIds(tokens) {
  const ids = []

  function visit(value, path) {
    if (!value || typeof value !== 'object' || Array.isArray(value)) return
    if ('$value' in value) {
      ids.push(path.join('.'))
      return
    }
    for (const [key, child] of Object.entries(value)) {
      if (key.startsWith('$')) continue
      visit(child, [...path, key])
    }
  }

  visit(tokens, [])
  return ids.sort()
}

function cssTokenValue(value) {
  if (typeof value === 'string' || typeof value === 'number') return String(value)
  if (value && typeof value === 'object' && typeof value.value === 'number' && typeof value.unit === 'string') {
    return `${value.value}${value.unit}`
  }
  throw new Error(`Unsupported design token value: ${JSON.stringify(value)}`)
}

export function renderTokenCss(tokens) {
  const entries = []
  const provenance = tokens.$extensions?.['org.govuk-design-md.provenance']
  const reviewedVersion = provenance?.govukFrontendVersion ?? 'unknown'
  const tabletPixels = tokens.govuk?.breakpoint?.tablet?.$value?.value
  const tabletMediaQuery = Number.isFinite(tabletPixels) ? `${tabletPixels / 16}em` : '40.0625em'

  function visit(value, path) {
    if (!value || typeof value !== 'object' || Array.isArray(value)) return
    if ('$value' in value) {
      entries.push([path.join('-'), cssTokenValue(value.$value)])
      return
    }
    for (const [key, child] of Object.entries(value)) {
      if (key.startsWith('$')) continue
      visit(child, [...path, key])
    }
  }

  visit(tokens, [])
  entries.sort(([left], [right]) => left.localeCompare(right, 'en-GB'))

  const functionalColourAliases = [
    ['brand-colour', 'color-brand'],
    ['text-colour', 'color-text'],
    ['secondary-text-colour', 'color-secondary-text'],
    ['body-background-colour', 'color-body-background'],
    ['template-background-colour', 'color-template-background'],
    ['surface-background-colour', 'color-surface-background'],
    ['surface-text-colour', 'color-surface-text'],
    ['surface-border-colour', 'color-surface-border'],
    ['border-colour', 'color-border'],
    ['input-border-colour', 'color-input-border'],
    ['hover-colour', 'color-hover'],
    ['link-colour', 'color-link'],
    ['link-hover-colour', 'color-link-hover'],
    ['link-visited-colour', 'color-link-visited'],
    ['link-active-colour', 'color-link-active'],
    ['focus-colour', 'color-focus'],
    ['focus-text-colour', 'color-focus-text'],
    ['error-colour', 'color-error'],
    ['success-colour', 'color-success']
  ]

  const declarations = entries.map(([id, value]) => `  --${id}: ${value};`)
  declarations.push('')
  declarations.push('  /* Familiar aliases for GOV.UK functional settings. */')
  for (const [alias, target] of functionalColourAliases) {
    declarations.push(`  --govuk-${alias}: var(--govuk-${target});`)
  }
  declarations.push('  --govuk-page-width: var(--govuk-layout-page-width);')
  declarations.push('  --govuk-page-gutter: var(--govuk-layout-gutter-half);')
  declarations.push('  --govuk-border-width: var(--govuk-border-standard);')
  declarations.push('  --govuk-border-width-wide: var(--govuk-border-wide);')
  declarations.push('  --govuk-border-width-narrow: var(--govuk-border-narrow);')
  declarations.push('  --govuk-border-width-form-element: var(--govuk-border-form-element);')
  declarations.push('  --govuk-focus-width: var(--govuk-border-focus);')

  for (const point of [0, 1, 2, 3]) {
    declarations.push(`  --govuk-spacing-responsive-${point}: var(--govuk-spacing-static-${point});`)
  }
  for (const point of [4, 5, 6, 7, 8, 9]) {
    declarations.push(`  --govuk-spacing-responsive-${point}: var(--govuk-spacing-responsive-${point}-mobile);`)
  }
  for (const point of [16, 19, 24, 27, 36, 48, 80]) {
    declarations.push(`  --govuk-font-size-${point}: var(--govuk-typography-scale-${point}-mobile-font-size);`)
    declarations.push(`  --govuk-line-height-${point}: var(--govuk-typography-scale-${point}-mobile-line-height);`)
  }

  const responsiveDeclarations = [
    '    --govuk-page-gutter: var(--govuk-layout-gutter);',
    ...[4, 5, 6, 7, 8, 9].map((point) => `    --govuk-spacing-responsive-${point}: var(--govuk-spacing-responsive-${point}-tablet);`),
    ...[16, 19, 24, 27, 36, 48, 80].flatMap((point) => [
      `    --govuk-font-size-${point}: var(--govuk-typography-scale-${point}-tablet-font-size);`,
      `    --govuk-line-height-${point}: var(--govuk-typography-scale-${point}-tablet-line-height);`
    ])
  ]

  return `/*
 * Generated from the reviewed GOV.UK Frontend ${reviewedVersion} token source.
 * This file does not include component CSS, GDS Transport, or identity assets.
 * Custom properties aid interoperability; GOV.UK Frontend remains authoritative.
 */
:root {
${declarations.join('\n')}
}

@media (min-width: ${tabletMediaQuery}) {
  :root {
${responsiveDeclarations.join('\n')}
  }
}
`
}

function bullets(items) {
  return items.map((item) => `- ${item}`).join('\n')
}

function inlineCodeList(items) {
  return items.length === 0 ? 'None' : items.map((item) => `\`${item}\``).join(', ')
}

const aiManagedBlockStart = '<!-- govuk-design-md:start -->'
const aiManagedBlockEnd = '<!-- govuk-design-md:end -->'

function aiRouterBody() {
  return `## GOV.UK Design System work

When a task creates or changes a GOV.UK-style user interface:

- Read \`DESIGN.md\` or \`GOVUK-DESIGN.md\`, then read user-owned \`DESIGN.local.md\` if present and use \`design/govuk/catalog.json\` to open only the relevant focused records.
- Preserve official semantic HTML, GOV.UK classes, content rules, accessibility relationships and progressive enhancement.
- Use an available framework adapter; otherwise translate syntax without changing the canonical DOM or behaviour.
- Do not infer GOV.UK conformance from visual similarity, tokens or a Tailwind, shadcn or Chakra theme.
- Do not introduce GDS Transport or GOV.UK identity assets unless the service is eligible to use them.`
}

export function renderAiAdapter(adapter) {
  if (adapter.id === 'cursor') {
    return `---
description: Apply reviewed GOV.UK Design System guidance when creating or changing GOV.UK-style user interfaces
alwaysApply: false
---

<!-- Generated by govuk-design-md from sources/ai-adapters.json. -->

${aiRouterBody()}
`
  }

  return `${aiManagedBlockStart}
<!-- Generated by govuk-design-md; content inside this block is package-managed. -->
${aiRouterBody()}
${aiManagedBlockEnd}
`
}

export function buildAiAdapterManifest(adapterSource) {
  return {
    schemaVersion: 1,
    reviewedAt: adapterSource.reviewedAt,
    adapters: adapterSource.adapters.map(({ id, name, sourceUrl, output, destination, mode }) => ({
      id,
      name,
      sourceUrl,
      source: output,
      destination,
      mode
    }))
  }
}

export function renderFrameworkAdapter(adapter, source) {
  const compatibility = adapter.compatibility.map((level) => `- \`${level}\``).join('\n')
  const sources = adapter.sourceUrls.map(({ name, url }) => `- [${name}](${url})`).join('\n')

  return `<!-- Generated by govuk-design-md. Edit sources/framework-adapters.json, then run npm run generate. -->

# ${adapter.name} adapter

**Status:** ${adapter.status[0].toUpperCase()}${adapter.status.slice(1)}
**Reviewed against:** GOV.UK Frontend ${source.govukFrontendVersion}
**Integration reviewed:** ${adapter.reviewedAt}

${adapter.description}

## Compatibility level

${compatibility}

These levels are scoped claims. They do not mean that a service is accessible, eligible to use GOV.UK identity assets, or conformant solely because it installed this adapter.

## Requirements

${bullets(adapter.requirements)}

## Asset setup

${bullets(adapter.assetSetup)}

## Page shell

${adapter.pageTemplateIntro}

\`\`\`${adapter.pageTemplateLanguage}
${adapter.pageTemplate}
\`\`\`

## Server rendering and official DOM

${bullets(adapter.rendering)}

## Progressive enhancement

${bullets(adapter.progressiveEnhancement)}

## JavaScript lifecycle

${bullets(adapter.lifecycle)}

${adapter.dynamicExampleIntro}

\`\`\`${adapter.dynamicExampleLanguage}
${adapter.dynamicExample}
\`\`\`

## Reference fixture

${adapter.fixtureDescription}

## Authoritative sources

${sources}
`
}

export function buildFrameworkAdapterManifest(adapterSource) {
  return {
    schemaVersion: 1,
    reviewedAt: adapterSource.reviewedAt,
    govukFrontendVersion: adapterSource.govukFrontendVersion,
    compatibilityLevels: ['guidance', 'token', 'markup', 'behaviour-tested'],
    adapters: adapterSource.adapters.map(({ id, name, status, output, fixture, compatibility }) => ({
      id,
      name,
      status,
      guidance: output,
      fixture,
      compatibility
    }))
  }
}

export function renderComponent(component) {
  const anatomy = component.anatomy
    .map((item) => `- **${item.name}${item.required ? ' (required)' : ''}:** ${item.description}`)
    .join('\n')
  const variants = component.variants
    .map((variant) => `| ${variant.name} | \`${variant.element}\` | ${inlineCodeList(variant.classes)} | ${variant.use} |`)
    .join('\n')
  const examples = component.htmlExamples
    .map((example) => `### ${example.name}\n\n\`\`\`html\n${example.html}\n\`\`\``)
    .join('\n\n')

  return `${generatedNotice}

# ${component.name}

**Status:** ${component.status[0].toUpperCase()}${component.status.slice(1)}  
**Reviewed against:** GOV.UK Frontend ${component.source.govukFrontendVersion} on ${component.source.reviewedAt}

${component.summary}

## When to use

${bullets(component.whenToUse)}

## When not to use

${bullets(component.whenNotToUse)}

## Anatomy

${anatomy}

## Variants

| Variant | Element | Classes | Use |
| --- | --- | --- | --- |
${variants}

## Behaviour and progressive enhancement

${bullets(component.behaviour)}

## Accessibility contract

${bullets(component.accessibility)}

## Content rules

${bullets(component.content)}

## Token references

${component.tokenRefs.map((token) => `- \`${token}\``).join('\n')}

## HTML examples

${examples}

## Authoritative sources

- [Usage guidance](${component.source.guidanceUrl})
- [GOV.UK Frontend ${component.source.govukFrontendVersion} implementation](${component.source.implementationUrl})
`
}

export function renderStyle(style) {
  const examples = style.examples
    .map((example) => `### ${example.name}\n\n\`\`\`${example.language}\n${example.code}\n\`\`\``)
    .join('\n\n')

  return `${generatedNotice}

# ${style.name}

**Foundation group:** ${style.group.replaceAll('-', ' ')}  
**Reviewed against:** GOV.UK Frontend ${style.source.govukFrontendVersion} on ${style.source.reviewedAt}

${style.summary}

## Rules

${bullets(style.rules)}

## Accessibility contract

${bullets(style.accessibility)}

## Restrictions and caveats

${bullets(style.restrictions)}

## Token references

${style.tokenRefs.length > 0 ? style.tokenRefs.map((token) => `- \`${token}\``).join('\n') : 'No portable token is appropriate for this guidance.'}

## Examples

${examples}

## Authoritative sources

- [Usage guidance](${style.source.guidanceUrl})
- [GOV.UK Frontend ${style.source.govukFrontendVersion} implementation](${style.source.implementationUrl})
`
}

export function renderPattern(pattern) {
  const componentLinks = pattern.componentRefs.length > 0
    ? pattern.componentRefs.map((id) => `- [${id}](../components/${id}.md)`).join('\n')
    : 'No GOV.UK Frontend component is prescribed by this pattern.'
  const relatedPatternLinks = pattern.relatedPatterns.length > 0
    ? pattern.relatedPatterns.map((id) => `- [${id}](./${id}.md)`).join('\n')
    : 'No related canonical pattern is currently recorded.'

  return `${generatedNotice}

# ${pattern.name}

**Pattern group:** ${pattern.group.replaceAll('-', ' ')}  
**Reviewed:** ${pattern.source.reviewedAt}

${pattern.summary}

## When to use

${bullets(pattern.whenToUse)}

## When not to use

${bullets(pattern.whenNotToUse)}

## Journey and implementation rules

${bullets(pattern.rules)}

## Accessibility and service safeguards

${bullets(pattern.accessibility)}

## Related components

${componentLinks}

## Related patterns

${relatedPatternLinks}

## Authoritative source

- [Usage guidance](${pattern.source.guidanceUrl})
`
}

export function renderDesign({ components, styles, patterns, packageMetadata, sourceManifest, frameworkAdapterSource }) {
  const inventories = sourceManifest.inventories
  const styleLinks = styles
    .map((style) => `- [${style.name}](design/govuk/styles/${style.id}.md)`)
    .join('\n')
  const componentLinks = components
    .map((component) => `- [${component.name}](design/govuk/components/${component.id}.md)${component.status === 'trial' ? ' — Trial' : ''}`)
    .join('\n')
  const patternGroupNames = {
    'ask-users-for': 'Ask users for',
    'help-users-to': 'Help users to',
    pages: 'Pages'
  }
  const patternLinks = Object.entries(patternGroupNames)
    .map(([group, heading]) => {
      const links = patterns
        .filter((pattern) => pattern.group === group)
        .map((pattern) => `- [${pattern.name}](design/govuk/patterns/${pattern.id}.md)`)
        .join('\n')
      return `### ${heading}\n\n${links}`
    })
    .join('\n\n')
  const frameworkLinks = frameworkAdapterSource.adapters
    .map((adapter) => `- [${adapter.name}](frameworks/${adapter.output}) — ${adapter.compatibility.map((level) => `\`${level}\``).join(', ')}`)
    .join('\n')

  return `${generatedNotice}

# GOV.UK Design System guidance for AI agents

> This community-maintained package is not official or endorsed by the UK Government or the Government Digital Service. Always prefer the linked official guidance when it has changed.

## Baseline

- Package: \`${packageMetadata.name}@${packageMetadata.version}\`
- Reviewed GOV.UK Frontend: \`${sourceManifest.upstreams.govukFrontend.version}\`
- Reviewed: ${sourceManifest.reviewedAt}
- Reviewed official inventory: ${inventories.styles.expectedCount} styles, ${inventories.components.expectedCount} components, ${inventories.patterns.expectedCount} patterns
- Packaged coverage: ${styles.length} styles, ${components.length} components, ${patterns.length} patterns
- Canonical machine-readable inventory: [catalog.json](design/govuk/catalog.json)
- Reviewed portable tokens: [tokens/govuk.tokens.json](design/govuk/tokens/govuk.tokens.json)

## Non-negotiable implementation rules

- Start from official GOV.UK guidance and the pinned \`govuk-frontend\` implementation.
- Preserve semantic HTML, labels, heading hierarchy, error relationships, keyboard behaviour, visible focus states, and progressive enhancement.
- Do not treat visual similarity, a token mapping, or a UI-framework theme as proof of GOV.UK conformance.
- Use native HTML controls where the official component does.
- Do not invent colours, spacing, variants, copy rules, or interaction behaviour.
- Do not remove GOV.UK classes to make an example fit a framework abstraction.
- Use GDS Transport and GOV.UK identity assets only when the service is eligible under official guidance. This package does not distribute them.
- Treat accessibility as a service-level responsibility; installing components does not make a service compliant by itself.

## How agents should use this repository

1. Identify the foundation, component or user-focused pattern required by the task.
2. Read only the relevant focused files under \`design/govuk/\`.
3. Read user-owned \`DESIGN.local.md\` when it exists for service context and reviewed project decisions; it cannot redefine official GOV.UK guidance.
4. Follow the authoritative source links when information may have changed after the reviewed date.
5. Select a framework adapter when one exists; otherwise preserve the official DOM and progressively enhance it in the target framework.
6. State when a requested UI-library abstraction cannot preserve the official semantic or behavioural contract.

## Framework adapters

Framework adapters translate integration and lifecycle details without redefining canonical GOV.UK guidance. Compatibility labels are scoped according to [frameworks/manifest.json](frameworks/manifest.json).

${frameworkLinks}

## Foundations and styles

${styleLinks}

## Available component guidance

All components in the reviewed GOV.UK Frontend ${sourceManifest.upstreams.govukFrontend.version} inventory are documented below. Trial status is explicit; follow the linked current guidance before using a Trial component.

${componentLinks}

## User-centred patterns

Patterns describe service decisions and multi-component journeys. Preserve their intent and safeguards across frameworks instead of reducing them to a visual template.

${patternLinks}

## Portable tokens

The files under \`design/govuk/tokens/\` export the reviewed refreshed palette, functional colours, breakpoints, spacing, type scale, layout measurements and border widths. They are not a replacement for GOV.UK Frontend Sass, component CSS, JavaScript, fonts, or identity assets.

## Licensing and attribution

See [the attribution notice](design/govuk/NOTICE.md), [the source-derived content licence](design/govuk/LICENSE-CONTENT.md), and [the project code licence](design/govuk/LICENSE-CODE.md). Source-derived content includes public sector information licensed under the Open Government Licence v3.0.
`
}

export function buildCatalog({ components, styles, patterns, packageMetadata, sourceManifest }) {
  const inventories = sourceManifest.inventories
  const canonicalCoverageComplete = styles.length === inventories.styles.expectedCount &&
    components.length === inventories.components.expectedCount &&
    patterns.length === inventories.patterns.expectedCount
  return {
    schemaVersion: 1,
    packageVersion: packageMetadata.version,
    govukFrontendVersion: sourceManifest.upstreams.govukFrontend.version,
    reviewedAt: sourceManifest.reviewedAt,
    status: canonicalCoverageComplete ? 'canonical-complete' : 'partial',
    coverage: {
      styles: {
        documented: styles.length,
        total: inventories.styles.expectedCount
      },
      components: {
        documented: components.length,
        total: inventories.components.expectedCount
      },
      patterns: {
        documented: patterns.length,
        total: inventories.patterns.expectedCount
      }
    },
    styles: styles.map((style) => ({
      id: style.id,
      name: style.name,
      group: style.group,
      summary: style.summary,
      path: `design/govuk/styles/${style.id}.md`,
      guidanceUrl: style.source.guidanceUrl,
      implementationUrl: style.source.implementationUrl,
      tokenRefs: style.tokenRefs
    })),
    components: components.map((component) => ({
      id: component.id,
      name: component.name,
      status: component.status,
      summary: component.summary,
      path: `design/govuk/components/${component.id}.md`,
      guidanceUrl: component.source.guidanceUrl,
      implementationUrl: component.source.implementationUrl,
      tokenRefs: component.tokenRefs
    })),
    patterns: patterns.map((pattern) => ({
      id: pattern.id,
      name: pattern.name,
      group: pattern.group,
      summary: pattern.summary,
      path: `design/govuk/patterns/${pattern.id}.md`,
      guidanceUrl: pattern.source.guidanceUrl,
      componentRefs: pattern.componentRefs,
      relatedPatterns: pattern.relatedPatterns
    }))
  }
}

export async function expectedGeneratedFiles(root = projectRoot) {
  const [components, styles, patterns, packageMetadata, sourceManifest, aiAdapterSource, frameworkAdapterSource, tokenJson, notice, contentLicense, codeLicense] = await Promise.all([
    loadComponents(root),
    loadStyles(root),
    loadPatterns(root),
    loadPackage(root),
    loadSourceManifest(root),
    loadAiAdapters(root),
    loadFrameworkAdapters(root),
    readFile(resolve(root, 'tokens', 'govuk.tokens.json'), 'utf8'),
    readFile(resolve(root, 'NOTICE.md'), 'utf8'),
    readFile(resolve(root, 'LICENSE-CONTENT.md'), 'utf8'),
    readFile(resolve(root, 'LICENSE-CODE.md'), 'utf8')
  ])
  const files = new Map()
  const tokenCss = renderTokenCss(JSON.parse(tokenJson))

  for (const component of components) {
    files.set(
      resolve(root, 'design', 'govuk', 'components', `${component.id}.md`),
      renderComponent(component)
    )
  }

  for (const style of styles) {
    files.set(
      resolve(root, 'design', 'govuk', 'styles', `${style.id}.md`),
      renderStyle(style)
    )
  }

  for (const pattern of patterns) {
    files.set(
      resolve(root, 'design', 'govuk', 'patterns', `${pattern.id}.md`),
      renderPattern(pattern)
    )
  }

  for (const adapter of aiAdapterSource.adapters) {
    files.set(resolveContained(resolve(root, 'adapters'), adapter.output), renderAiAdapter(adapter))
  }
  files.set(
    resolve(root, 'adapters', 'manifest.json'),
    `${JSON.stringify(buildAiAdapterManifest(aiAdapterSource), null, 2)}\n`
  )

  for (const adapter of frameworkAdapterSource.adapters) {
    files.set(
      resolveContained(resolve(root, 'frameworks'), adapter.output),
      renderFrameworkAdapter(adapter, frameworkAdapterSource)
    )
  }
  files.set(
    resolve(root, 'frameworks', 'manifest.json'),
    `${JSON.stringify(buildFrameworkAdapterManifest(frameworkAdapterSource), null, 2)}\n`
  )

  files.set(resolve(root, 'DESIGN.md'), renderDesign({ components, styles, patterns, packageMetadata, sourceManifest, frameworkAdapterSource }))
  const catalog = `${JSON.stringify(buildCatalog({ components, styles, patterns, packageMetadata, sourceManifest }), null, 2)}\n`
  files.set(resolve(root, 'catalog.json'), catalog)
  files.set(resolve(root, 'design', 'govuk', 'catalog.json'), catalog)
  files.set(resolve(root, 'tokens', 'govuk.css'), tokenCss)
  files.set(resolve(root, 'design', 'govuk', 'tokens', 'govuk.tokens.json'), tokenJson)
  files.set(resolve(root, 'design', 'govuk', 'tokens', 'govuk.css'), tokenCss)
  files.set(resolve(root, 'design', 'govuk', 'NOTICE.md'), notice)
  files.set(resolve(root, 'design', 'govuk', 'LICENSE-CONTENT.md'), contentLicense)
  files.set(resolve(root, 'design', 'govuk', 'LICENSE-CODE.md'), codeLicense)

  return files
}
