import { readFile, readdir } from 'node:fs/promises'
import { dirname, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const moduleDirectory = dirname(fileURLToPath(import.meta.url))

export const projectRoot = resolve(moduleDirectory, '..', '..')
export const generatedNotice = '<!-- Generated by govuk-design-md. Edit src/catalog records, then run npm run generate. -->'

function resolveContained(base, path) {
  const resolvedBase = resolve(base)
  const resolvedPath = resolve(resolvedBase, path)
  if (resolvedPath === resolvedBase || !resolvedPath.startsWith(`${resolvedBase}${sep}`)) {
    throw new Error(`generated path escapes its output directory: ${path}`)
  }
  return resolvedPath
}

export async function readJson(path) {
  return JSON.parse(await readFile(path, 'utf8'))
}

export async function loadSourceManifest(root = projectRoot) {
  return readJson(resolve(root, 'sources', 'govuk.json'))
}

export async function loadComponents(root = projectRoot) {
  const directory = resolve(root, 'src', 'catalog', 'components')
  const filenames = (await readdir(directory))
    .filter((filename) => filename.endsWith('.json'))
    .sort()

  const components = await Promise.all(
    filenames.map((filename) => readJson(resolve(directory, filename)))
  )

  return components.sort((left, right) => left.name.localeCompare(right.name, 'en-GB'))
}

export async function loadStyles(root = projectRoot) {
  const directory = resolve(root, 'src', 'catalog', 'styles')
  const filenames = (await readdir(directory))
    .filter((filename) => filename.endsWith('.json'))
    .sort()

  const styles = await Promise.all(
    filenames.map((filename) => readJson(resolve(directory, filename)))
  )

  return styles.sort((left, right) => left.name.localeCompare(right.name, 'en-GB'))
}

export async function loadPatterns(root = projectRoot) {
  const directory = resolve(root, 'src', 'catalog', 'patterns')
  const filenames = (await readdir(directory))
    .filter((filename) => filename.endsWith('.json'))
    .sort()

  const patterns = await Promise.all(
    filenames.map((filename) => readJson(resolve(directory, filename)))
  )

  return patterns.sort((left, right) => left.name.localeCompare(right.name, 'en-GB'))
}

export async function loadPackage(root = projectRoot) {
  return readJson(resolve(root, 'package.json'))
}

export async function loadTokens(root = projectRoot) {
  return readJson(resolve(root, 'tokens', 'govuk.tokens.json'))
}

export async function loadAiAdapters(root = projectRoot) {
  return readJson(resolve(root, 'sources', 'ai-adapters.json'))
}

export async function loadFrameworkAdapters(root = projectRoot) {
  return readJson(resolve(root, 'sources', 'framework-adapters.json'))
}

export async function loadUiFrameworkAdapters(root = projectRoot) {
  return readJson(resolve(root, 'sources', 'ui-framework-adapters.json'))
}

export function tokenIds(tokens) {
  const ids = []

  function visit(value, path) {
    if (!value || typeof value !== 'object' || Array.isArray(value)) return
    if ('$value' in value) {
      ids.push(path.join('.'))
      return
    }
    for (const [key, child] of Object.entries(value)) {
      if (key.startsWith('$')) continue
      visit(child, [...path, key])
    }
  }

  visit(tokens, [])
  return ids.sort()
}

function cssTokenValue(value) {
  if (typeof value === 'string' || typeof value === 'number') return String(value)
  if (value && typeof value === 'object' && typeof value.value === 'number' && typeof value.unit === 'string') {
    return `${value.value}${value.unit}`
  }
  throw new Error(`Unsupported design token value: ${JSON.stringify(value)}`)
}

export function renderTokenCss(tokens) {
  const entries = []
  const provenance = tokens.$extensions?.['org.govuk-design-md.provenance']
  const reviewedVersion = provenance?.govukFrontendVersion ?? 'unknown'
  const tabletPixels = tokens.govuk?.breakpoint?.tablet?.$value?.value
  const tabletMediaQuery = Number.isFinite(tabletPixels) ? `${tabletPixels / 16}em` : '40.0625em'

  function visit(value, path) {
    if (!value || typeof value !== 'object' || Array.isArray(value)) return
    if ('$value' in value) {
      entries.push([path.join('-'), cssTokenValue(value.$value)])
      return
    }
    for (const [key, child] of Object.entries(value)) {
      if (key.startsWith('$')) continue
      visit(child, [...path, key])
    }
  }

  visit(tokens, [])
  entries.sort(([left], [right]) => left.localeCompare(right, 'en-GB'))

  const functionalColourAliases = [
    ['brand-colour', 'color-brand'],
    ['text-colour', 'color-text'],
    ['secondary-text-colour', 'color-secondary-text'],
    ['body-background-colour', 'color-body-background'],
    ['template-background-colour', 'color-template-background'],
    ['surface-background-colour', 'color-surface-background'],
    ['surface-text-colour', 'color-surface-text'],
    ['surface-border-colour', 'color-surface-border'],
    ['border-colour', 'color-border'],
    ['input-border-colour', 'color-input-border'],
    ['hover-colour', 'color-hover'],
    ['link-colour', 'color-link'],
    ['link-hover-colour', 'color-link-hover'],
    ['link-visited-colour', 'color-link-visited'],
    ['link-active-colour', 'color-link-active'],
    ['focus-colour', 'color-focus'],
    ['focus-text-colour', 'color-focus-text'],
    ['error-colour', 'color-error'],
    ['success-colour', 'color-success']
  ]

  const declarations = entries.map(([id, value]) => `  --${id}: ${value};`)
  declarations.push('')
  declarations.push('  /* Familiar aliases for GOV.UK functional settings. */')
  for (const [alias, target] of functionalColourAliases) {
    declarations.push(`  --govuk-${alias}: var(--govuk-${target});`)
  }
  declarations.push('  --govuk-page-width: var(--govuk-layout-page-width);')
  declarations.push('  --govuk-page-gutter: var(--govuk-layout-gutter-half);')
  declarations.push('  --govuk-border-width: var(--govuk-border-standard);')
  declarations.push('  --govuk-border-width-wide: var(--govuk-border-wide);')
  declarations.push('  --govuk-border-width-narrow: var(--govuk-border-narrow);')
  declarations.push('  --govuk-border-width-form-element: var(--govuk-border-form-element);')
  declarations.push('  --govuk-focus-width: var(--govuk-border-focus);')

  for (const point of [0, 1, 2, 3]) {
    declarations.push(`  --govuk-spacing-responsive-${point}: var(--govuk-spacing-static-${point});`)
  }
  for (const point of [4, 5, 6, 7, 8, 9]) {
    declarations.push(`  --govuk-spacing-responsive-${point}: var(--govuk-spacing-responsive-${point}-mobile);`)
  }
  for (const point of [16, 19, 24, 27, 36, 48, 80]) {
    declarations.push(`  --govuk-font-size-${point}: var(--govuk-typography-scale-${point}-mobile-font-size);`)
    declarations.push(`  --govuk-line-height-${point}: var(--govuk-typography-scale-${point}-mobile-line-height);`)
  }

  const responsiveDeclarations = [
    '    --govuk-page-gutter: var(--govuk-layout-gutter);',
    ...[4, 5, 6, 7, 8, 9].map((point) => `    --govuk-spacing-responsive-${point}: var(--govuk-spacing-responsive-${point}-tablet);`),
    ...[16, 19, 24, 27, 36, 48, 80].flatMap((point) => [
      `    --govuk-font-size-${point}: var(--govuk-typography-scale-${point}-tablet-font-size);`,
      `    --govuk-line-height-${point}: var(--govuk-typography-scale-${point}-tablet-line-height);`
    ])
  ]

  return `/*
 * Generated from the reviewed GOV.UK Frontend ${reviewedVersion} token source.
 * This file does not include component CSS, GDS Transport, or identity assets.
 * Custom properties aid interoperability; GOV.UK Frontend remains authoritative.
 */
:root {
${declarations.join('\n')}
}

@media (min-width: ${tabletMediaQuery}) {
  :root {
${responsiveDeclarations.join('\n')}
  }
}
`
}

function bullets(items) {
  return items.map((item) => `- ${item}`).join('\n')
}

function inlineCodeList(items) {
  return items.length === 0 ? 'None' : items.map((item) => `\`${item}\``).join(', ')
}

const aiManagedBlockStart = '<!-- govuk-design-md:start -->'
const aiManagedBlockEnd = '<!-- govuk-design-md:end -->'

function aiRouterBody() {
  return `## GOV.UK Design System work

When a task creates or changes a GOV.UK-style user interface:

- Read \`DESIGN.md\` or \`GOVUK-DESIGN.md\`, then read user-owned \`DESIGN.local.md\` if present and use \`design/govuk/catalog.json\` to open only the relevant focused records.
- Preserve official semantic HTML, GOV.UK classes, content rules, accessibility relationships and progressive enhancement.
- Use an available framework adapter; otherwise translate syntax without changing the canonical DOM or behaviour.
- Do not infer GOV.UK conformance from visual similarity, tokens or a Tailwind, shadcn or Chakra theme.
- Do not introduce GDS Transport or GOV.UK identity assets unless the service is eligible to use them.`
}

export function renderAiAdapter(adapter) {
  if (adapter.id === 'cursor') {
    return `---
description: Apply reviewed GOV.UK Design System guidance when creating or changing GOV.UK-style user interfaces
alwaysApply: false
---

<!-- Generated by govuk-design-md from sources/ai-adapters.json. -->

${aiRouterBody()}
`
  }

  return `${aiManagedBlockStart}
<!-- Generated by govuk-design-md; content inside this block is package-managed. -->
${aiRouterBody()}
${aiManagedBlockEnd}
`
}

export function buildAiAdapterManifest(adapterSource) {
  return {
    schemaVersion: 1,
    reviewedAt: adapterSource.reviewedAt,
    adapters: adapterSource.adapters.map(({ id, name, sourceUrl, output, destination, mode }) => ({
      id,
      name,
      sourceUrl,
      source: output,
      destination,
      mode
    }))
  }
}

export function renderFrameworkAdapter(adapter, source) {
  const compatibility = adapter.compatibility.map((level) => `- \`${level}\``).join('\n')
  const sources = adapter.sourceUrls.map(({ name, url }) => `- [${name}](${url})`).join('\n')

  return `<!-- Generated by govuk-design-md. Edit sources/framework-adapters.json, then run npm run generate. -->

# ${adapter.name} adapter

**Status:** ${adapter.status[0].toUpperCase()}${adapter.status.slice(1)}
**Reviewed against:** GOV.UK Frontend ${source.govukFrontendVersion}
**Integration reviewed:** ${adapter.reviewedAt}

${adapter.description}

## Compatibility level

${compatibility}

These levels are scoped claims. They do not mean that a service is accessible, eligible to use GOV.UK identity assets, or conformant solely because it installed this adapter.

## Requirements

${bullets(adapter.requirements)}

## Asset setup

${bullets(adapter.assetSetup)}

## Page shell

${adapter.pageTemplateIntro}

\`\`\`${adapter.pageTemplateLanguage}
${adapter.pageTemplate}
\`\`\`

## Server rendering and official DOM

${bullets(adapter.rendering)}

## Progressive enhancement

${bullets(adapter.progressiveEnhancement)}

## JavaScript lifecycle

${bullets(adapter.lifecycle)}

${adapter.dynamicExampleIntro}

\`\`\`${adapter.dynamicExampleLanguage}
${adapter.dynamicExample}
\`\`\`

## Reference fixture

${adapter.fixtureDescription}

## Authoritative sources

${sources}
`
}

export function buildFrameworkAdapterManifest(adapterSource) {
  return {
    schemaVersion: 1,
    reviewedAt: adapterSource.reviewedAt,
    govukFrontendVersion: adapterSource.govukFrontendVersion,
    compatibilityLevels: ['guidance', 'token', 'markup', 'behaviour-tested'],
    adapters: adapterSource.adapters.map(({ id, name, status, output, fixture, compatibility }) => ({
      id,
      name,
      status,
      guidance: output,
      fixture,
      compatibility
    }))
  }
}

export function renderUiFrameworkAdapter(adapter, source) {
  const compatibility = adapter.compatibility.map((level) => `- \`${level}\``).join('\n')
  const sources = adapter.sourceUrls.map(({ name, url }) => `- [${name}](${url})`).join('\n')

  return `<!-- Generated by govuk-design-md. Edit sources/ui-framework-adapters.json, then run npm run generate. -->

# ${adapter.name} adapter

**Status:** ${adapter.status[0].toUpperCase()}${adapter.status.slice(1)}
**Reviewed against:** GOV.UK Frontend ${source.govukFrontendVersion}
**Implementation reviewed:** ${adapter.implementation.name} ${adapter.implementation.version} on ${adapter.reviewedAt}

${adapter.description}

## Compatibility level

${compatibility}

These levels describe this adapter's bounded evidence. They do not mean that ${adapter.implementation.name} itself supplies GOV.UK components, that a service is accessible, or that a theme makes an implementation conformant.

## Scope and requirements

${bullets(adapter.requirements)}

## Installation and build order

${bullets(adapter.installation)}

## Preflight and cascade

${bullets(adapter.preflight)}

## Token mapping

${bullets(adapter.tokens)}

## Official components and behaviour

${bullets(adapter.components)}

## Browser support

${bullets(adapter.browserSupport)}

## Build example

${adapter.buildExampleIntro}

\`\`\`${adapter.buildExampleLanguage}
${adapter.buildExample}
\`\`\`

${adapter.markupExampleIntro}

\`\`\`${adapter.markupExampleLanguage}
${adapter.markupExample}
\`\`\`

## Reference fixture

${adapter.fixtureDescription}

## Authoritative sources

${sources}
`
}

export function buildUiFrameworkAdapterManifest(adapterSource) {
  return {
    schemaVersion: 1,
    reviewedAt: adapterSource.reviewedAt,
    govukFrontendVersion: adapterSource.govukFrontendVersion,
    compatibilityLevels: ['guidance', 'token', 'markup', 'behaviour-tested'],
    compatibilityMatrix: 'compatibility.md',
    adapters: adapterSource.adapters.map((adapter) => ({
      id: adapter.id,
      name: adapter.name,
      status: adapter.status,
      implementation: adapter.implementation,
      guidance: adapter.output,
      files: [adapter.output, adapter.tokenOutput],
      tokenMapping: adapter.tokenOutput,
      fixture: adapter.fixture,
      compatibility: adapter.compatibility,
      compatibilityBoundary: adapter.compatibilityBoundary
    }))
  }
}

function compatibilityCell(adapter, level) {
  return adapter.compatibility.includes(level) ? 'Included' : 'Not claimed'
}

export function renderUiFrameworkCompatibility(adapterSource) {
  const rows = adapterSource.adapters
    .map((adapter) => `| [${adapter.name}](${adapter.output}) | ${compatibilityCell(adapter, 'guidance')} | ${compatibilityCell(adapter, 'token')} | ${compatibilityCell(adapter, 'markup')} | ${compatibilityCell(adapter, 'behaviour-tested')} | ${adapter.compatibilityBoundary} |`)
    .join('\n')

  return `<!-- Generated by govuk-design-md. Edit sources/ui-framework-adapters.json, then run npm run generate. -->

# UI-framework compatibility matrix

These labels describe the reviewed evidence supplied by each adapter, not general compatibility or service conformance. A token or theme mapping cannot supply GOV.UK semantics, content rules, accessibility or progressive enhancement.

| Adapter | Guidance | Token | Markup | Behaviour tested | Evidence boundary |
| --- | --- | --- | --- | --- | --- |
${rows}

## Levels

- **Guidance:** routes implementers to the applicable canonical and official GOV.UK guidance.
- **Token:** maps reviewed values for bounded service-owned styling without claiming component equivalence.
- **Markup:** the adapter demonstrates the official semantic DOM and class contract, including documented fallbacks where the UI framework cannot preserve it.
- **Behaviour tested:** the reference fixture exercises the retained GOV.UK JavaScript, keyboard, focus and progressive-enhancement contract.

No level makes an application conformant by itself. Teams must test the complete service against their users, supported browsers and accessibility requirements.
`
}

function remFromPixels(token) {
  const value = token?.$value
  if (!value || value.unit !== 'px' || !Number.isFinite(value.value)) {
    throw new Error(`Tailwind breakpoint token must be a pixel dimension: ${JSON.stringify(token)}`)
  }
  return `${Number((value.value / 16).toFixed(4))}rem`
}

export function renderTailwindTheme(tokens, {
  description = 'This Tailwind CSS 4 bridge is for service-owned extensions, not component recreation.'
} = {}) {
  const govuk = tokens.govuk
  const declarations = []
  const palette = govuk.color.palette

  for (const [name, value] of Object.entries(palette)) {
    if ('$value' in value) {
      declarations.push(`  --color-govuk-${name}: var(--govuk-color-palette-${name});`)
      continue
    }
    for (const tokenName of Object.keys(value).filter((key) => !key.startsWith('$'))) {
      const suffix = tokenName === 'primary' ? '' : `-${tokenName}`
      declarations.push(`  --color-govuk-${name}${suffix}: var(--govuk-color-palette-${name}-${tokenName});`)
    }
  }

  for (const name of Object.keys(govuk.color).filter((key) => !key.startsWith('$') && key !== 'palette')) {
    declarations.push(`  --color-govuk-${name}: var(--govuk-color-${name});`)
  }
  declarations.push('  --color-govuk-background: var(--govuk-color-body-background);')
  declarations.push('  --color-govuk-surface: var(--govuk-color-surface-background);')

  for (const name of Object.keys(govuk.spacing.static).filter((key) => !key.startsWith('$'))) {
    declarations.push(`  --spacing-govuk-${name}: var(--govuk-spacing-static-${name});`)
  }
  for (const name of Object.keys(govuk.spacing.responsive).filter((key) => !key.startsWith('$'))) {
    declarations.push(`  --spacing-govuk-responsive-${name}: var(--govuk-spacing-responsive-${name});`)
  }
  declarations.push('  --spacing-govuk-gutter: var(--govuk-page-gutter);')

  for (const name of Object.keys(govuk.typography.scale).filter((key) => !key.startsWith('$'))) {
    declarations.push(`  --text-govuk-${name}: var(--govuk-font-size-${name});`)
    declarations.push(`  --text-govuk-${name}--line-height: var(--govuk-line-height-${name});`)
  }
  for (const name of Object.keys(govuk.typography.weight).filter((key) => !key.startsWith('$'))) {
    declarations.push(`  --font-weight-govuk-${name}: var(--govuk-typography-weight-${name});`)
  }

  for (const [name, token] of Object.entries(govuk.breakpoint).filter(([key]) => !key.startsWith('$'))) {
    declarations.push(`  --breakpoint-govuk-${name}: ${remFromPixels(token)};`)
  }
  declarations.push('  --container-govuk-page: var(--govuk-layout-page-width);')

  return `/*
 * Generated from the reviewed GOV.UK Frontend ${tokens.$extensions?.['org.govuk-design-md.provenance']?.govukFrontendVersion ?? 'unknown'} token source.
 * ${description}
 * Keep the canonical token file at the relative path below or update the import.
 */
@import "../../design/govuk/tokens/govuk.css";

@theme static {
${declarations.join('\n')}
}
`
}

export function renderShadcnTheme(tokens) {
  return renderTailwindTheme(tokens, {
    description: 'This Tailwind CSS 4 bridge supports locally owned shadcn-style service extensions, not GOV.UK component recreation.'
  })
}

function renderChakraTokens(entries, indentation = '        ') {
  return entries
    .map(([name, value]) => `${indentation}${JSON.stringify(name)}: { value: ${JSON.stringify(value)} }`)
    .join(',\n')
}

function renderChakraValues(entries, indentation = '      ') {
  return entries
    .map(([name, value]) => `${indentation}${JSON.stringify(name)}: ${JSON.stringify(value)}`)
    .join(',\n')
}

export function renderChakraSystem(tokens) {
  const govuk = tokens.govuk
  const palette = []
  for (const [name, value] of Object.entries(govuk.color.palette)) {
    if ('$value' in value) {
      palette.push([`govuk-${name}`, `var(--govuk-color-palette-${name})`])
      continue
    }
    for (const tokenName of Object.keys(value).filter((key) => !key.startsWith('$'))) {
      const suffix = tokenName === 'primary' ? '' : `-${tokenName}`
      palette.push([`govuk-${name}${suffix}`, `var(--govuk-color-palette-${name}-${tokenName})`])
    }
  }

  const functionalColors = Object.keys(govuk.color)
    .filter((key) => !key.startsWith('$') && key !== 'palette')
    .map((name) => [`govuk-${name}`, `var(--govuk-color-${name})`])
  functionalColors.push(['govuk-background', 'var(--govuk-color-body-background)'])
  functionalColors.push(['govuk-surface', 'var(--govuk-color-surface-background)'])

  const spacing = Object.keys(govuk.spacing.static)
    .filter((key) => !key.startsWith('$'))
    .map((name) => [`govuk-${name}`, `var(--govuk-spacing-static-${name})`])
  for (const name of Object.keys(govuk.spacing.responsive).filter((key) => !key.startsWith('$'))) {
    spacing.push([`govuk-responsive-${name}`, `var(--govuk-spacing-responsive-${name})`])
  }
  spacing.push(['govuk-gutter', 'var(--govuk-page-gutter)'])

  const fontSizes = Object.keys(govuk.typography.scale)
    .filter((key) => !key.startsWith('$'))
    .map((name) => [`govuk-${name}`, `var(--govuk-font-size-${name})`])
  const lineHeights = Object.keys(govuk.typography.scale)
    .filter((key) => !key.startsWith('$'))
    .map((name) => [`govuk-${name}`, `var(--govuk-line-height-${name})`])
  const fontWeights = Object.keys(govuk.typography.weight)
    .filter((key) => !key.startsWith('$'))
    .map((name) => [`govuk-${name}`, `var(--govuk-typography-weight-${name})`])
  const borderWidths = Object.keys(govuk.border)
    .filter((key) => !key.startsWith('$'))
    .map((name) => [`govuk-${name}`, `var(--govuk-border-${name})`])
  const breakpoints = Object.entries(govuk.breakpoint)
    .filter(([key]) => !key.startsWith('$'))
    .map(([name, token]) => [`govuk-${name}`, `${token.$value.value}${token.$value.unit}`])

  return `/*
 * Generated from the reviewed GOV.UK Frontend ${tokens.$extensions?.['org.govuk-design-md.provenance']?.govukFrontendVersion ?? 'unknown'} token source.
 * This reset-free Chakra UI 3 system is for service-owned extensions, not component recreation.
 * Load design/govuk/tokens/govuk.css before rendering components that consume these values.
 */
import { createSystem, defaultBaseConfig, defineConfig } from '@chakra-ui/react'

const govukChakraConfig = defineConfig({
  cssVarsPrefix: 'govuk-chakra',
  disableLayers: true,
  preflight: false,
  globalCss: {},
  theme: {
    breakpoints: {
${renderChakraValues(breakpoints)}
    },
    tokens: {
      colors: {
${renderChakraTokens([...palette, ...functionalColors])}
      },
      spacing: {
${renderChakraTokens(spacing)}
      },
      sizes: {
        "govuk-page": { value: "var(--govuk-layout-page-width)" }
      },
      fontSizes: {
${renderChakraTokens(fontSizes)}
      },
      lineHeights: {
${renderChakraTokens(lineHeights)}
      },
      fontWeights: {
${renderChakraTokens(fontWeights)}
      },
      borderWidths: {
${renderChakraTokens(borderWidths)}
      }
    }
  }
})

export const govukChakraSystem = createSystem(defaultBaseConfig, govukChakraConfig)
`
}

export function renderComponent(component) {
  const anatomy = component.anatomy
    .map((item) => `- **${item.name}${item.required ? ' (required)' : ''}:** ${item.description}`)
    .join('\n')
  const variants = component.variants
    .map((variant) => `| ${variant.name} | \`${variant.element}\` | ${inlineCodeList(variant.classes)} | ${variant.use} |`)
    .join('\n')
  const examples = component.htmlExamples
    .map((example) => `### ${example.name}\n\n\`\`\`html\n${example.html}\n\`\`\``)
    .join('\n\n')

  return `${generatedNotice}

# ${component.name}

**Status:** ${component.status[0].toUpperCase()}${component.status.slice(1)}  
**Reviewed against:** GOV.UK Frontend ${component.source.govukFrontendVersion} on ${component.source.reviewedAt}

${component.summary}

## When to use

${bullets(component.whenToUse)}

## When not to use

${bullets(component.whenNotToUse)}

## Anatomy

${anatomy}

## Variants

| Variant | Element | Classes | Use |
| --- | --- | --- | --- |
${variants}

## Behaviour and progressive enhancement

${bullets(component.behaviour)}

## Accessibility contract

${bullets(component.accessibility)}

## Content rules

${bullets(component.content)}

## Token references

${component.tokenRefs.map((token) => `- \`${token}\``).join('\n')}

## HTML examples

${examples}

## Authoritative sources

- [Usage guidance](${component.source.guidanceUrl})
- [GOV.UK Frontend ${component.source.govukFrontendVersion} implementation](${component.source.implementationUrl})
`
}

export function renderStyle(style) {
  const examples = style.examples
    .map((example) => `### ${example.name}\n\n\`\`\`${example.language}\n${example.code}\n\`\`\``)
    .join('\n\n')

  return `${generatedNotice}

# ${style.name}

**Foundation group:** ${style.group.replaceAll('-', ' ')}  
**Reviewed against:** GOV.UK Frontend ${style.source.govukFrontendVersion} on ${style.source.reviewedAt}

${style.summary}

## Rules

${bullets(style.rules)}

## Accessibility contract

${bullets(style.accessibility)}

## Restrictions and caveats

${bullets(style.restrictions)}

## Token references

${style.tokenRefs.length > 0 ? style.tokenRefs.map((token) => `- \`${token}\``).join('\n') : 'No portable token is appropriate for this guidance.'}

## Examples

${examples}

## Authoritative sources

- [Usage guidance](${style.source.guidanceUrl})
- [GOV.UK Frontend ${style.source.govukFrontendVersion} implementation](${style.source.implementationUrl})
`
}

export function renderPattern(pattern) {
  const componentLinks = pattern.componentRefs.length > 0
    ? pattern.componentRefs.map((id) => `- [${id}](../components/${id}.md)`).join('\n')
    : 'No GOV.UK Frontend component is prescribed by this pattern.'
  const relatedPatternLinks = pattern.relatedPatterns.length > 0
    ? pattern.relatedPatterns.map((id) => `- [${id}](./${id}.md)`).join('\n')
    : 'No related canonical pattern is currently recorded.'

  return `${generatedNotice}

# ${pattern.name}

**Pattern group:** ${pattern.group.replaceAll('-', ' ')}  
**Reviewed:** ${pattern.source.reviewedAt}

${pattern.summary}

## When to use

${bullets(pattern.whenToUse)}

## When not to use

${bullets(pattern.whenNotToUse)}

## Journey and implementation rules

${bullets(pattern.rules)}

## Accessibility and service safeguards

${bullets(pattern.accessibility)}

## Related components

${componentLinks}

## Related patterns

${relatedPatternLinks}

## Authoritative source

- [Usage guidance](${pattern.source.guidanceUrl})
`
}

export function renderDesign({ components, styles, patterns, packageMetadata, sourceManifest, frameworkAdapterSource, uiFrameworkAdapterSource }) {
  const inventories = sourceManifest.inventories
  const styleLinks = styles
    .map((style) => `- [${style.name}](design/govuk/styles/${style.id}.md)`)
    .join('\n')
  const componentLinks = components
    .map((component) => `- [${component.name}](design/govuk/components/${component.id}.md)${component.status === 'trial' ? ' — Trial' : ''}`)
    .join('\n')
  const patternGroupNames = {
    'ask-users-for': 'Ask users for',
    'help-users-to': 'Help users to',
    pages: 'Pages'
  }
  const patternLinks = Object.entries(patternGroupNames)
    .map(([group, heading]) => {
      const links = patterns
        .filter((pattern) => pattern.group === group)
        .map((pattern) => `- [${pattern.name}](design/govuk/patterns/${pattern.id}.md)`)
        .join('\n')
      return `### ${heading}\n\n${links}`
    })
    .join('\n\n')
  const frameworkLinks = frameworkAdapterSource.adapters
    .map((adapter) => `- [${adapter.name}](frameworks/${adapter.output}) — ${adapter.compatibility.map((level) => `\`${level}\``).join(', ')}`)
    .join('\n')
  const uiFrameworkLinks = uiFrameworkAdapterSource.adapters
    .map((adapter) => `- [${adapter.name}](ui-frameworks/${adapter.output}) — ${adapter.compatibility.map((level) => `\`${level}\``).join(', ')}`)
    .join('\n')

  return `${generatedNotice}

# GOV.UK Design System guidance for AI agents

> This community-maintained package is not official or endorsed by the UK Government or the Government Digital Service. Always prefer the linked official guidance when it has changed.

## Baseline

- Package: \`${packageMetadata.name}@${packageMetadata.version}\`
- Reviewed GOV.UK Frontend: \`${sourceManifest.upstreams.govukFrontend.version}\`
- Reviewed: ${sourceManifest.reviewedAt}
- Reviewed official inventory: ${inventories.styles.expectedCount} styles, ${inventories.components.expectedCount} components, ${inventories.patterns.expectedCount} patterns
- Packaged coverage: ${styles.length} styles, ${components.length} components, ${patterns.length} patterns
- Canonical machine-readable inventory: [catalog.json](design/govuk/catalog.json)
- Reviewed portable tokens: [tokens/govuk.tokens.json](design/govuk/tokens/govuk.tokens.json)

## Non-negotiable implementation rules

- Start from official GOV.UK guidance and the pinned \`govuk-frontend\` implementation.
- Preserve semantic HTML, labels, heading hierarchy, error relationships, keyboard behaviour, visible focus states, and progressive enhancement.
- Do not treat visual similarity, a token mapping, or a UI-framework theme as proof of GOV.UK conformance.
- Use native HTML controls where the official component does.
- Do not invent colours, spacing, variants, copy rules, or interaction behaviour.
- Do not remove GOV.UK classes to make an example fit a framework abstraction.
- Use GDS Transport and GOV.UK identity assets only when the service is eligible under official guidance. This package does not distribute them.
- Treat accessibility as a service-level responsibility; installing components does not make a service compliant by itself.

## How agents should use this repository

1. Identify the foundation, component or user-focused pattern required by the task.
2. Read only the relevant focused files under \`design/govuk/\`.
3. Read user-owned \`DESIGN.local.md\` when it exists for service context and reviewed project decisions; it cannot redefine official GOV.UK guidance.
4. Follow the authoritative source links when information may have changed after the reviewed date.
5. Select a framework adapter when one exists; otherwise preserve the official DOM and progressively enhance it in the target framework.
6. State when a requested UI-library abstraction cannot preserve the official semantic or behavioural contract.

## Framework adapters

Framework adapters translate integration and lifecycle details without redefining canonical GOV.UK guidance. Compatibility labels are scoped according to [frameworks/manifest.json](frameworks/manifest.json).

${frameworkLinks}

## UI-framework adapters

UI-framework adapters map bounded integration concerns without replacing official GOV.UK components. Compatibility labels are scoped according to [ui-frameworks/manifest.json](ui-frameworks/manifest.json).

See the [UI-framework compatibility matrix](ui-frameworks/compatibility.md) for the evidence boundary behind each label.

${uiFrameworkLinks}

## Foundations and styles

${styleLinks}

## Available component guidance

All components in the reviewed GOV.UK Frontend ${sourceManifest.upstreams.govukFrontend.version} inventory are documented below. Trial status is explicit; follow the linked current guidance before using a Trial component.

${componentLinks}

## User-centred patterns

Patterns describe service decisions and multi-component journeys. Preserve their intent and safeguards across frameworks instead of reducing them to a visual template.

${patternLinks}

## Portable tokens

The files under \`design/govuk/tokens/\` export the reviewed refreshed palette, functional colours, breakpoints, spacing, type scale, layout measurements and border widths. They are not a replacement for GOV.UK Frontend Sass, component CSS, JavaScript, fonts, or identity assets.

## Licensing and attribution

See [the attribution notice](design/govuk/NOTICE.md), [the source-derived content licence](design/govuk/LICENSE-CONTENT.md), and [the project code licence](design/govuk/LICENSE-CODE.md). Source-derived content includes public sector information licensed under the Open Government Licence v3.0.
`
}

export function buildCatalog({ components, styles, patterns, packageMetadata, sourceManifest }) {
  const inventories = sourceManifest.inventories
  const canonicalCoverageComplete = styles.length === inventories.styles.expectedCount &&
    components.length === inventories.components.expectedCount &&
    patterns.length === inventories.patterns.expectedCount
  return {
    schemaVersion: 1,
    packageVersion: packageMetadata.version,
    govukFrontendVersion: sourceManifest.upstreams.govukFrontend.version,
    reviewedAt: sourceManifest.reviewedAt,
    status: canonicalCoverageComplete ? 'canonical-complete' : 'partial',
    coverage: {
      styles: {
        documented: styles.length,
        total: inventories.styles.expectedCount
      },
      components: {
        documented: components.length,
        total: inventories.components.expectedCount
      },
      patterns: {
        documented: patterns.length,
        total: inventories.patterns.expectedCount
      }
    },
    styles: styles.map((style) => ({
      id: style.id,
      name: style.name,
      group: style.group,
      summary: style.summary,
      path: `design/govuk/styles/${style.id}.md`,
      guidanceUrl: style.source.guidanceUrl,
      implementationUrl: style.source.implementationUrl,
      tokenRefs: style.tokenRefs
    })),
    components: components.map((component) => ({
      id: component.id,
      name: component.name,
      status: component.status,
      summary: component.summary,
      path: `design/govuk/components/${component.id}.md`,
      guidanceUrl: component.source.guidanceUrl,
      implementationUrl: component.source.implementationUrl,
      tokenRefs: component.tokenRefs
    })),
    patterns: patterns.map((pattern) => ({
      id: pattern.id,
      name: pattern.name,
      group: pattern.group,
      summary: pattern.summary,
      path: `design/govuk/patterns/${pattern.id}.md`,
      guidanceUrl: pattern.source.guidanceUrl,
      componentRefs: pattern.componentRefs,
      relatedPatterns: pattern.relatedPatterns
    }))
  }
}

export function renderOpenDesign({ components, styles, patterns, packageMetadata, sourceManifest, tokens, tokenCss, notice }) {
  // Keep the export independent of sibling files and preserve fenced examples.
  const embed = (markdown) => {
    let fenced = false
    return markdown.replace(`${generatedNotice}\n\n`, '').trim().split('\n').map((line) => {
      if (line.startsWith('```')) fenced = !fenced
      return !fenced && /^#{1,3} /.test(line) ? `##${line}` : line
    }).join('\n')
  }
  const foundations = (ids) => styles.filter((style) => ids.includes(style.id)).map((style) => embed(renderStyle(style))).join('\n\n')
  const typography = styles.filter((style) => style.group === 'typography').map((style) => embed(renderStyle(style))).join('\n\n')
  const patternGuidance = patterns.map((pattern) => embed(renderPattern(pattern))
    .replace(/\]\(\.\.\/components\/([a-z-]+)\.md\)/g, '](https://design-system.service.gov.uk/components/$1/)')
    .replace(/\]\(\.\/([a-z-]+)\.md\)/g, '](https://design-system.service.gov.uk/patterns/$1/)')).join('\n\n')
  const color = tokens.govuk.color
  return `---
name: GOV.UK Design System
description: Reviewed GOV.UK service design guidance, portable tokens and accessible component contracts.
category: Government & Public Services
surface: web
colors:
  primary: "${color.link.$value}"
  background: "${color['body-background'].$value}"
  text: "${color.text.$value}"
  accent: "${color.focus.$value}"
---

# GOV.UK Design System

> Category: Government & Public Services
> Clear, accessible public services built from reviewed GOV.UK guidance.

${generatedNotice}

## 1. Visual Theme & Atmosphere

This standalone OpenDesign import is generated from govuk-design-md@${packageMetadata.version}, reviewed against GOV.UK Frontend ${sourceManifest.upstreams.govukFrontend.version} on ${sourceManifest.reviewedAt}. It includes ${styles.length} foundations, ${components.length} components and ${patterns.length} patterns. Guidance and examples are embedded; no repository-relative files are required.

Start from the official GOV.UK components and preserve their semantic HTML, classes, keyboard behaviour, focus states and progressive enhancement. Visual similarity and token mappings alone do not establish GOV.UK conformance. Use the linked official guidance to check for changes after the review date.

${notice.replace(/^# .+\n/, '').trim()}

## 2. Color Palette & Roles

${foundations(['colour'])}

### Portable token CSS

The following reviewed CSS custom properties include colour roles, typography, spacing and breakpoints. These are portable values, not replacement component styles. Install govuk-frontend@${sourceManifest.upstreams.govukFrontend.version} for the component implementation; obtain eligible fonts and identity assets through the official distribution.

\`\`\`css
${tokenCss.trim()}
\`\`\`

## 3. Typography

${typography}

## 4. Layout & Spacing

${foundations(['layout', 'spacing', 'page-template', 'section-break'])}

## 5. Components

${components.map((component) => embed(renderComponent(component))).join('\n\n')}

## 6. Motion & Interaction

Use the component-specific behaviour and progressive-enhancement contracts above. Preserve visible keyboard focus and native control semantics. Essential content and service actions must remain available without JavaScript; initialise GOV.UK Frontend modules for supported enhancements.

## 7. Iconography & Imagery

${foundations(['images'])}

Use the documented component markup for icons. GOV.UK identity assets and GDS Transport have eligibility requirements and are not embedded in this file.

## 8. Voice & Tone

Follow the content rules in each component and the journey rules below. Use clear sentence-case action labels that describe the outcome, meaningful labels and specific error messages. Preserve the distinction between links for navigation and buttons for actions.

## 9. Edge Cases & Variations

Apply the following patterns to the full service journey, including validation, errors, confirmation and accessibility. Treat accessibility as a service-level responsibility and test the implemented service with users and assistive technology.

${patternGuidance}
`
}

export async function expectedGeneratedFiles(root = projectRoot) {
  const [components, styles, patterns, packageMetadata, sourceManifest, aiAdapterSource, frameworkAdapterSource, uiFrameworkAdapterSource, tokenJson, notice, contentLicense, codeLicense] = await Promise.all([
    loadComponents(root),
    loadStyles(root),
    loadPatterns(root),
    loadPackage(root),
    loadSourceManifest(root),
    loadAiAdapters(root),
    loadFrameworkAdapters(root),
    loadUiFrameworkAdapters(root),
    readFile(resolve(root, 'tokens', 'govuk.tokens.json'), 'utf8'),
    readFile(resolve(root, 'NOTICE.md'), 'utf8'),
    readFile(resolve(root, 'LICENSE-CONTENT.md'), 'utf8'),
    readFile(resolve(root, 'LICENSE-CODE.md'), 'utf8')
  ])
  const files = new Map()
  const tokenCss = renderTokenCss(JSON.parse(tokenJson))
  files.set(resolve(root, 'adapters/open-design/DESIGN.md'), renderOpenDesign({
    components, styles, patterns, packageMetadata, sourceManifest,
    tokens: JSON.parse(tokenJson), tokenCss, notice
  }))

  for (const component of components) {
    files.set(
      resolve(root, 'design', 'govuk', 'components', `${component.id}.md`),
      renderComponent(component)
    )
  }

  for (const style of styles) {
    files.set(
      resolve(root, 'design', 'govuk', 'styles', `${style.id}.md`),
      renderStyle(style)
    )
  }

  for (const pattern of patterns) {
    files.set(
      resolve(root, 'design', 'govuk', 'patterns', `${pattern.id}.md`),
      renderPattern(pattern)
    )
  }

  for (const adapter of aiAdapterSource.adapters) {
    files.set(resolveContained(resolve(root, 'adapters'), adapter.output), renderAiAdapter(adapter))
  }
  files.set(
    resolve(root, 'adapters', 'manifest.json'),
    `${JSON.stringify(buildAiAdapterManifest(aiAdapterSource), null, 2)}\n`
  )

  for (const adapter of frameworkAdapterSource.adapters) {
    files.set(
      resolveContained(resolve(root, 'frameworks'), adapter.output),
      renderFrameworkAdapter(adapter, frameworkAdapterSource)
    )
  }
  files.set(
    resolve(root, 'frameworks', 'manifest.json'),
    `${JSON.stringify(buildFrameworkAdapterManifest(frameworkAdapterSource), null, 2)}\n`
  )

  for (const adapter of uiFrameworkAdapterSource.adapters) {
    files.set(
      resolveContained(resolve(root, 'ui-frameworks'), adapter.output),
      renderUiFrameworkAdapter(adapter, uiFrameworkAdapterSource)
    )
    if (adapter.id === 'tailwind') {
      files.set(
        resolveContained(resolve(root, 'ui-frameworks'), adapter.tokenOutput),
        renderTailwindTheme(JSON.parse(tokenJson))
      )
    } else if (adapter.id === 'shadcn') {
      files.set(
        resolveContained(resolve(root, 'ui-frameworks'), adapter.tokenOutput),
        renderShadcnTheme(JSON.parse(tokenJson))
      )
    } else if (adapter.id === 'chakra') {
      files.set(
        resolveContained(resolve(root, 'ui-frameworks'), adapter.tokenOutput),
        renderChakraSystem(JSON.parse(tokenJson))
      )
    } else {
      throw new Error(`unsupported UI-framework adapter generator: ${adapter.id}`)
    }
  }
  files.set(
    resolve(root, 'ui-frameworks', 'manifest.json'),
    `${JSON.stringify(buildUiFrameworkAdapterManifest(uiFrameworkAdapterSource), null, 2)}\n`
  )
  files.set(
    resolve(root, 'ui-frameworks', 'compatibility.md'),
    renderUiFrameworkCompatibility(uiFrameworkAdapterSource)
  )

  files.set(resolve(root, 'DESIGN.md'), renderDesign({ components, styles, patterns, packageMetadata, sourceManifest, frameworkAdapterSource, uiFrameworkAdapterSource }))
  const catalog = `${JSON.stringify(buildCatalog({ components, styles, patterns, packageMetadata, sourceManifest }), null, 2)}\n`
  files.set(resolve(root, 'catalog.json'), catalog)
  files.set(resolve(root, 'design', 'govuk', 'catalog.json'), catalog)
  files.set(resolve(root, 'tokens', 'govuk.css'), tokenCss)
  files.set(resolve(root, 'design', 'govuk', 'tokens', 'govuk.tokens.json'), tokenJson)
  files.set(resolve(root, 'design', 'govuk', 'tokens', 'govuk.css'), tokenCss)
  files.set(resolve(root, 'design', 'govuk', 'NOTICE.md'), notice)
  files.set(resolve(root, 'design', 'govuk', 'LICENSE-CONTENT.md'), contentLicense)
  files.set(resolve(root, 'design', 'govuk', 'LICENSE-CODE.md'), codeLicense)

  return files
}
